import "./globals.css";
import { ReactNode } from "react";

export const metadata = {
  title: "Assessment app based on Next",
  description: "Assessment app generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
